### ISSUE TITLE
Error failed to attach XDP program: Operation not supported

### ISSUE THREAD

**Issue by PinkD** [hack3ric/mimic#11]
Install mimic from [aur](https://aur.archlinux.org/packages/mimic-bpf) and call `systemctl start mimic@eth0.service`

Error:
<img width="949" alt="{7257BB2B-CE3A-4785-998F-90983A5384C8}" src="https://github.com/user-attachments/assets/74a050fd-6e17-409e-88e1-df9c31d5a7fb">

Host:
<img width="631" alt="image" src="https://github.com/user-attachments/assets/d8f5ac80-8cb7-4dc6-9852-b561c8d99a16">

BTW it's working on my pc with same os and kernel version.

**Comment by hack3ric** [comment]
Could you try running other XDP programs like those in https://github.com/xdp-project/xdp-tools? Just simple loading would help, e.g. `xdp-bench pass eth0`.

I don't have Aliyun machines to work with, and I suspect it's their virtualization's problem (IIRC they use custom hypervisor and has caused some problems elsewhere).

**Comment by PinkD** [comment]
```text
$ xdp-bench pass eth0
  libbpf: Kernel error message: virtio_net: Can't set XDP while host is implementing GRO_HW/CSUM, disable GRO_HW/CSUM first
Failed to attach XDP program: Operation not supported
```

**Comment by hack3ric** [comment]
What about `xdp-bench pass --xdp-mode skb eth0`? Also the output of `ethtool -k eth0` will help.

The error message comes from https://github.com/torvalds/linux/blob/e70140ba0d2b1a30467d4af6bcfe761327b9ec95/drivers/net/virtio_net.c#L5891, and _maybe_ Aliyun is to blame. This renders all XDP code unable to run on their platforms, and one should really file a ticket to them.

You could try to turn off some or all of the checksum features (those containing `checksum`, `offload`, `gro`, `gso`) and see if it helps.

**Comment by PinkD** [comment]
I try to turn off all the checksum features but some failed with error `Could not change any device features`
![image](https://github.com/user-attachments/assets/49b1caf3-f606-483e-96b6-cbb4bc441847)

> `xdp-bench pass --xdp-mode skb eth0`

The cmd succeeds and the output indicates the driver is `virtio_net`

> and maybe Aliyun is to blame.

I agree

I'll try to start a vm with qemu to test if mimic works inside vm

**Comment by PinkD** [comment]
> I'll try to start a vm with qemu to test if mimic works inside vm

Result: 

<img width="753" alt="{A7B95AEF-8179-4987-9CFD-4B41A987BA72}" src="https://github.com/user-attachments/assets/0825a495-16ab-4b71-a47d-7810dbde55ba">

qemu parameters: 
```bash
qemu-system-x86_64 \
  -enable-kvm \
# ...
  -device e1000,netdev=network1,mac=aa:aa:aa:aa:aa:aa \
  -netdev tap,id=network1,ifname=test-eth,script=no,downscript=no \
# ...
  -cpu host -smp 4 \
  -m 4G
```

Seems mimic is not compatible with vm network drivers

**Comment by hack3ric** [comment]
> Seems mimic is not compatible with vm network drivers

No, you are using the default native loader, which is driver dependent. SKB mode will work. In fact my PC's NIC reports not supporting native mode as well, but it runs Mimic normally.

As for virtio drivers, all of my current VPSes runs Mimic well, as well as my Debian libvirt VM in my PC (which also uses QEMU) so it should not be the case.

I'll investigate it further tomorrow how those modes are selected by default, and we could add an option that forces the use of SKB mode for compatibility.

**Comment by PinkD** [comment]
> In fact my PC's NIC reports not supporting native mode as well, but it runs Mimic normally.

Yes, I just started mimic in the vm and it didn't report any error.

**Comment by hack3ric** [comment]
Added XDP attach mode option in https://github.com/hack3ric/mimic/commit/fd0fe2f480835fefb59ae30295b8c249b39fb161, which should be available in the next minor release.
