### ISSUE TITLE
Can't Connect With Wireguard on KVM VMs

### ISSUE THREAD

**Issue by Handsome1080P** [hack3ric/mimic#5]
### TEST Environment

> 2 Debian 12 VMs on KVM based on Archlinux and VMs installed virt-io NIC drivers.
> Server Specs: 5950X + 128G RAM

#### Net Conf
> root@NetServer:~# ifconfig
> enp1s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 192.168.25.20  netmask 255.255.255.0  broadcast 192.168.25.255
>         inet6 fe80::5054:ff:feab:b1bb  prefixlen 64  scopeid 0x20<link>
>         ether 52:54:00:ab:b1:bb  txqueuelen 1000  (Ethernet)
>         RX packets 3503  bytes 226850 (221.5 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 5898  bytes 419994 (410.1 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> enp2s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 192.168.100.30  netmask 255.255.255.0  broadcast 192.168.100.255
>         inet6 fe80::5054:ff:fe81:b2b2  prefixlen 64  scopeid 0x20<link>
>         ether 52:54:00:81:b2:b2  txqueuelen 1000  (Ethernet)
>         RX packets 4105  bytes 1191523 (1.1 MiB)
>         RX errors 0  dropped 9  overruns 0  frame 0
>         TX packets 1622  bytes 225465 (220.1 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         inet6 ::1  prefixlen 128  scopeid 0x10<host>
>         loop  txqueuelen 1000  (Local Loopback)
>         RX packets 80  bytes 6480 (6.3 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 80  bytes 6480 (6.3 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420
>         inet 10.0.0.1  netmask 255.255.255.0  destination 10.0.0.1
>         unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
>         RX packets 67  bytes 8688 (8.4 KiB)
>         RX errors 20  dropped 0  overruns 0  frame 20
>         TX packets 66  bytes 7536 (7.3 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

#### IP Route

> root@NetServer:~# ip route show
> default via 192.168.100.254 dev enp2s0 proto dhcp src 192.168.100.30 metric 1024
> 10.0.0.0/24 dev wg0 proto kernel scope link src 10.0.0.1
> 192.168.25.0/24 dev enp1s0 proto kernel scope link src 192.168.25.20
> 192.168.100.0/24 dev enp2s0 proto kernel scope link src 192.168.100.30 metric 1024
> 192.168.100.254 dev enp2s0 proto dhcp scope link src 192.168.100.30 metric 1024
> 

#### WG Conf

> root@NetServer:~# cat /etc/wireguard/wg0.conf
> [Interface]
> PrivateKey = +PNMnVcbR+KYp6w7e4Y1ICUNpCvwm7aneMc3raI0GEk=
> Address = 10.0.0.1/24
> MTU = 1420
> Table = off
> ListenPort = 1000
> 
> [Peer]
> PublicKey = 32FZpB7GyD3TmHuNnglDpkIqzCB4QpSDhecGPKLNlg4=
> PresharedKey = CtN04NspOMWBOLN4kLluIngCfdf+Z+MEBDCQomOgjXE=
> AllowedIPs = 10.0.0.2/32

#### MIMIC

> root@NetServer:~# mimic run -f local=192.168.100.30:1000 enp2s0
>  Info Mimic successfully deployed on enp2s0
>  Info   settings: handshake 2:3, keepalive 180:10:3:600
>  Info   filter: local=192.168.100.30:1000
>  Info 192.168.100.30:1000 => 192.168.100.10:1000 :: accepting connection
>  Info 192.168.100.30:1000 => 192.168.100.10:1000 :: connection established

#### Net Conf

> root@debian12:~# ifconfig
> ens192: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>         inet 192.168.30.157  netmask 255.255.255.0  broadcast 192.168.30.255
>         inet6 fe80::250:56ff:fea6:3205  prefixlen 64  scopeid 0x20<link>
>         ether 00:50:56:a6:32:05  txqueuelen 1000  (Ethernet)
>         RX packets 1921  bytes 171610 (167.5 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 1624  bytes 231675 (226.2 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
>         inet 127.0.0.1  netmask 255.0.0.0
>         inet6 ::1  prefixlen 128  scopeid 0x10<host>
>         loop  txqueuelen 1000  (Local Loopback)
>         RX packets 482  bytes 181640 (177.3 KiB)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 482  bytes 181640 (177.3 KiB)
>         TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
> 
> wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420
>         inet 10.0.0.2  netmask 255.255.255.0  destination 10.0.0.2
>         unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
>         RX packets 7  bytes 824 (824.0 B)
>         RX errors 0  dropped 0  overruns 0  frame 0
>         TX packets 129  bytes 17724 (17.3 KiB)
>         TX errors 0  dropped 13 overruns 0  carrier 0  collisions 0

#### IP Route
> root@debian12:~# ip rout show
> default via 192.168.30.254 dev ens192 proto dhcp src 192.168.30.157 metric 1024
> 10.0.0.0/24 dev wg0 proto kernel scope link src 10.0.0.2
> 114.114.114.114 via 192.168.30.254 dev ens192 proto dhcp src 192.168.30.157 metric 1024
> 192.168.30.0/24 dev ens192 proto kernel scope link src 192.168.30.157 metric 1024
> 192.168.30.254 dev ens192 proto dhcp scope link src 192.168.30.157 metric 1024
> 223.5.5.5 via 192.168.30.254 dev ens192 proto dhcp src 192.168.30.157 metric 1024

#### WG Conf

> root@debian12:~# cat /etc/wireguard/wg0.conf
> [Interface]
> PrivateKey = GNiWvijEStDV756zyD7lReUJZ44e79DczsdtqqYr9WY=
> Address = 10.0.0.2/24
> MTU = 1420
> Table = off
> ListenPort = 1000
> 
> [Peer]
> PublicKey = ZmOiLeimRV5vcaXu5tmAYQAXPZHONf5GWUXVg9JRHkQ=
> PresharedKey = CtN04NspOMWBOLN4kLluIngCfdf+Z+MEBDCQomOgjXE=
> AllowedIPs = 0.0.0.0/0, ::/0
> Endpoint = 192.168.100.30:1000
> 

#### MIMIC
> root@debian12:~# mimic run -f remote=192.168.100.30:1000 ens192
>  Info Mimic successfully deployed on ens192
>  Info   settings: handshake 2:3, keepalive 180:10:3:600
>  Info   filter: remote=192.168.100.30:1000
>  Info 192.168.30.157:1000 => 192.168.100.30:1000 :: initializing connection
>  Info 192.168.30.157:1000 => 192.168.100.30:1000 :: connection established
>  Warn 192.168.30.157:1000 => 192.168.100.30:1000 :: connection destroyed (timed out)
>  Info 192.168.30.157:1000 => 192.168.100.30:1000 :: initializing connection
>  Info 192.168.30.157:1000 => 192.168.100.30:1000 :: connection established

### TEST With MIMIC

> root@debian12:~# ping 10.0.0.1
> PING 10.0.0.1 (10.0.0.1) 56(84) bytes of data.
### TEST Without MIMIC
> root@debian12:~# ping 10.0.0.1
> PING 10.0.0.1 (10.0.0.1) 56(84) bytes of data.
> 64 bytes from 10.0.0.1: icmp_seq=1 ttl=128 time=68.7 ms
> 64 bytes from 10.0.0.1: icmp_seq=2 ttl=128 time=69.8 ms
> 64 bytes from 10.0.0.1: icmp_seq=3 ttl=128 time=69.7 ms
> 64 bytes from 10.0.0.1: icmp_seq=4 ttl=128 time=70.1 ms
>

**Comment by Handsome1080P** [comment]
MIMIC latest version 0.4.0

**Comment by Handsome1080P** [comment]
tcpdump got the logs about tcp,but server side not redirect the traffic to wg server.
![image](https://github.com/hack3ric/mimic/assets/13675031/468a2571-39c2-4ca1-a665-ee00d29767c6)

**Comment by Handsome1080P** [comment]
And if my udp server not host on the same machine,how to use MIMIC. Server side set to backend server IP and interface set to the comunication interface of client?

**Comment by hack3ric** [comment]
Please check:
- if WireGuard really uses the IP and interface you specified on Mimic
- your VM gateway (between 192.168.30.0/24 and 192.168.100.0/24) is handling packets correctly

It seems you are using some kind of NAT (192.168.30.157 -> 192.168.100.10). Also try to run Mimic with `-vv` so TCP traffic is visible.

> And if my udp server not host on the same machine,how to use MIMIC. Server side set to backend server IP and interface set to the comunication interface of client?

Not possible at the moment. raw socket sending control packets currently binds to IPs on the interface. But this could be possible to implement in the future.

**Comment by Handsome1080P** [comment]
![image](https://github.com/hack3ric/mimic/assets/13675031/572a3a06-3cc1-4e2a-bc08-6be5abd771a8)


> Please check:
> 
> * if WireGuard really uses the IP and interface you specified on Mimic
> * your VM gateway (between 192.168.30.0/24 and 192.168.100.0/24) is handling packets correctly
> 
> It seems you are using some kind of NAT (192.168.30.157 -> 192.168.100.10). Also try to run Mimic with `-vv` so TCP traffic is visible.
> 
> > And if my udp server not host on the same machine,how to use MIMIC. Server side set to backend server IP and interface set to the comunication interface of client?
> 
> Not possible at the moment. raw socket sending control packets currently binds to IPs on the interface. But this could be possible to implement in the future.

**Comment by Handsome1080P** [comment]
No any traffic.There is no firewall between two vms
Client:
![image](https://github.com/hack3ric/mimic/assets/13675031/f0dc4751-0212-4ee5-b7c3-867be2957840)
Server:
![image](https://github.com/hack3ric/mimic/assets/13675031/374bb30b-278b-4988-85d0-ad9afd402a21)

**Comment by hack3ric** [comment]
Trace font color is actually really close to background in a lot of terminals. There are there and you can see it if you copy paste it. (please use Markdown code blocks for posting logs) I will fix this visual bug next version. 

It seems you still have some kind of conflict (like your previous issue). These RSTs won't come out of nowhere.

**Comment by Handsome1080P** [comment]
it say connected,but wg can't ping each other.

**Comment by Handsome1080P** [comment]
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: recv - len=128, ACK, seq=0e4ee41e, ack=0c5c0bbf
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: sent - len=128, ACK, seq=0c5c190b, ack=0e4ee3a4
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: recv - len=128, ACK, seq=0e4ee49e, ack=0c5c0c3f
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: sent - len=128, ACK, seq=0c5c198b, ack=0e4ee424
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: recv - len=128, ACK, seq=0e4ee51e, ack=0c5c0cbf
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: sent - len=128, ACK, seq=0c5c1a0b, ack=0e4ee4a4
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: recv - len=128, ACK, seq=0e4ee59e, ack=0c5c0d3f
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: sent - len=128, ACK, seq=0c5c1a8b, ack=0e4ee524
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: recv - len=128, ACK, seq=0e4ee61e, ack=0c5c0dbf
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: sent - len=128, ACK, seq=0c5c1b0b, ack=0e4ee5a4
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: recv - len=128, ACK, seq=0e4ee69e, ack=0c5c0e3f
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: sent - len=128, ACK, seq=0c5c1b8b, ack=0e4ee624
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: recv - len=128, ACK, seq=0e4ee71e, ack=0c5c0ebf
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: sent - len=128, ACK, seq=0c5c1c0b, ack=0e4ee6a4
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: recv - len=128, ACK, seq=0e4ee79e, ack=0c5c0f3f
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: sent - len=128, ACK, seq=0c5c1c8b, ack=0e4ee724
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: recv - len=128, ACK, seq=0e4ee81e, ack=0c5c0fbf
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: sent - len=128, ACK, seq=0c5c1d0b, ack=0e4ee7a4
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: recv - len=128, ACK, seq=0e4ee89e, ack=0c5c103f
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: sent - len=128, ACK, seq=0c5c1d8b, ack=0e4ee824
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: recv - len=128, ACK, seq=0e4ee91e, ack=0c5c10bf
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: sent - len=128, ACK, seq=0c5c1e0b, ack=0e4ee8a4
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: recv - len=128, ACK, seq=0e4ee99e, ack=0c5c113f
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: sent - len=128, ACK, seq=0c5c1e8b, ack=0e4ee924
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: recv - len=128, ACK, seq=0e4eea1e, ack=0c5c11bf
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: sent - len=128, ACK, seq=0c5c1f0b, ack=0e4ee9a4
> Trace 192.168.100.30:1000 => 192.168.100.10:1000 :: recv - len=128, ACK, seq=0e4eea9e, ack=0c5c123f
>

**Comment by Handsome1080P** [comment]
yeah,the color issue.

**Comment by hack3ric** [comment]
What about client's trace?

**Comment by Handsome1080P** [comment]
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=128, ACK, seq=babb17d4, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=128, ACK, seq=babb1854, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb18d4, ack=6e006b2a
>

**Comment by Handsome1080P** [comment]
Only sent no recv
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=128, ACK, seq=babb1854, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb18d4, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb1968, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb19fc, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb1a90, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb1b24, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb1bb8, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb1c4c, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb1ce0, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb1d74, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb1e08, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb1e9c, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb1f30, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb1fc4, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb2058, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb20ec, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb2180, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb2214, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb22a8, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb233c, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb23d0, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb2464, ack=6e006b2a
> Trace 192.168.30.157:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=babb

**Comment by hack3ric** [comment]
I am almost sure this is your configuration's problem, since Mimic will not send RST,ACK packets, only OS will.

Can I check your NAT configuration?

**Comment by Handsome1080P** [comment]
> I am almost sure this is your configuration's problem, since Mimic will not send RST,ACK packets, only OS will.
> 
> Can I check your NAT configuration?

two vms for test no firewall ,pure system.and gateway 192.168.100.10 only one iptables.
192.168.100.10 on eth0.gateway same as debian 12

> -A POSTROUTING -o eth0 -j MASQUERADE

**Comment by Handsome1080P** [comment]
and try another debian 12 vm client,got this issue.

> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: sent - len=0, ACK, seq=be437d87, ack=40a55eeb
>  Info 192.168.133.189:1000 => 192.168.100.30:1000 :: connection established
> Debug 192.168.133.189:1000 => 192.168.100.30:1000 :: pktbuf_consume: trying to bind 192.168.133.189
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=be437d87, ack=40a55eeb
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=2, SYN,ACK, seq=40a55ee8, ack=be437d87
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: sent - len=0, RST, seq=be437e1b, ack=00000000
>  Warn 192.168.133.189:1000 => 192.168.100.30:1000 :: connection destroyed (unknown)
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=6, RST, seq=40a55eeb, ack=00000000
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=6, RST, seq=40a55eeb, ack=00000000
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=2, SYN,ACK, seq=40a55ee8, ack=be437d87
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: sent - len=0, RST, seq=be437d87, ack=00000000
>  Info 192.168.133.189:1000 => 192.168.100.30:1000 :: initializing connection
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: sent - len=0, SYN, seq=9586533e, ack=00000000
> Debug 192.168.133.189:1000 => 192.168.100.30:1000 :: userspace received packet, udp.len=156, csum_partial=1
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=2, SYN,ACK, seq=6f8f2676, ack=9586533f
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: sent - len=0, ACK, seq=9586533f, ack=6f8f2679
>  Info 192.168.133.189:1000 => 192.168.100.30:1000 :: connection established
> Debug 192.168.133.189:1000 => 192.168.100.30:1000 :: pktbuf_consume: trying to bind 192.168.133.189
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=9586533f, ack=6f8f2679
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=2, SYN,ACK, seq=6f8f2676, ack=9586533f
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: sent - len=0, RST, seq=958653d3, ack=00000000
>  Warn 192.168.133.189:1000 => 192.168.100.30:1000 :: connection destroyed (unknown)
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=6, RST, seq=6f8f2679, ack=00000000
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=6, RST, seq=6f8f2679, ack=00000000
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=2, SYN,ACK, seq=6f8f2676, ack=9586533f
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: sent - len=0, RST, seq=9586533f, ack=00000000
>  Info 192.168.133.189:1000 => 192.168.100.30:1000 :: initializing connection
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: sent - len=0, SYN, seq=062be55d, ack=00000000
> Debug 192.168.133.189:1000 => 192.168.100.30:1000 :: userspace received packet, udp.len=156, csum_partial=1
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=2, SYN,ACK, seq=059c614d, ack=062be55e
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: sent - len=0, ACK, seq=062be55e, ack=059c6150
>  Info 192.168.133.189:1000 => 192.168.100.30:1000 :: connection established
> Debug 192.168.133.189:1000 => 192.168.100.30:1000 :: pktbuf_consume: trying to bind 192.168.133.189
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: sent - len=148, ACK, seq=062be55e, ack=059c6150
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=2, SYN,ACK, seq=059c614d, ack=062be55e
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: sent - len=0, RST, seq=062be5f2, ack=00000000
>  Warn 192.168.133.189:1000 => 192.168.100.30:1000 :: connection destroyed (unknown)
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=6, RST, seq=059c6150, ack=00000000
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=6, RST, seq=059c6150, ack=00000000
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=2, SYN,ACK, seq=059c614d, ack

**Comment by Handsome1080P** [comment]
server logs:

>  Warn 192.168.100.30:1000 => 192.168.100.10:991 :: connection destroyed (received RST)
> Trace 192.168.100.30:1000 => 192.168.100.10:989 :: recv - len=6, RST,ACK, seq=3102aae8, ack=8b0edc64
>  Warn 192.168.100.30:1000 => 192.168.100.10:989 :: connection destroyed (received RST)
> Trace 192.168.100.30:1000 => 192.168.100.10:987 :: recv - len=6, ACK, seq=3c1ad9f8, ack=72ac2609
> Trace 192.168.100.30:1000 => 192.168.100.10:986 :: recv - len=6, ACK, seq=773fb2b4, ack=da1fc163
> Trace 192.168.100.30:1000 => 192.168.100.10:985 :: recv - len=0, SYN, seq=97c0fddf, ack=00000000
>  Info 192.168.100.30:1000 => 192.168.100.10:985 :: accepting connection
> Trace 192.168.100.30:1000 => 192.168.100.10:985 :: sent - len=0, SYN,ACK, seq=5b5c6052, ack=97c0fde0
> Trace 192.168.100.30:1000 => 192.168.100.10:985 :: recv - len=6, ACK, seq=97c0fde0, ack=5b5c6053
>  Info 192.168.100.30:1000 => 192.168.100.10:985 :: connection established
> Trace 192.168.100.30:1000 => 192.168.100.10:990 :: recv - len=6, RST,ACK, seq=8f32e907, ack=3bbcd8b4
>  Warn 192.168.100.30:1000 => 192.168.100.10:990 :: connection destroyed (received RST)
> Trace 192.168.100.30:1000 => 192.168.100.10:985 :: recv - len=6, ACK, seq=97c0fde0, ack=5b5c6053
> Trace 192.168.100.30:1000 => 192.168.100.10:985 :: recv - len=6, ACK, seq=97c0fde0, ack=5b5c6053
> Trace 192.168.100.30:1000 => 192.168.100.10:985 :: recv - len=6, ACK, seq=97c0fde0, ack=5b5c6053
> Trace 192.168.100.30:1000 => 192.168.100.10:985 :: recv - len=6, ACK, seq=97c0fde0, ack=5b5c6053
> Trace 192.168.100.30:1000 => 192.168.100.10:988 :: recv - len=6, RST,ACK, seq=8426851d, ack=36f5d6dd
>  Warn 192.168.100.30:1000 => 192.168.100.10:988 :: connection destroyed (received RST)
> Trace 192.168.100.30:1000 => 192.168.100.10:986 :: recv - len=6, ACK, seq=773fb2b4, ack=da1fc163
> Trace 192.168.100.30:1000 => 192.168.100.10:984 :: recv - len=0, SYN, seq=4d94bda3, ack=00000000
>  Info 192.168.100.30:1000 => 192.168.100.10:984 :: accepting connection
> Trace 192.168.100.30:1000 => 192.168.100.10:984 :: sent - len=0, SYN,ACK, seq=d89391fe, ack=4d94bda4
> Trace 192.168.100.30:1000 => 192.168.100.10:985 :: recv - len=6, ACK, seq=97c0fde0, ack=5b5c6053
> Trace 192.168.100.30:1000 => 192.168.100.10:984 :: recv - len=6, ACK, seq=4d94bda4, ack=d89391ff
>  Info 192.168.100.30:1000 => 192.168.100.10:984 :: connection established
> Trace 192.168.100.30:1000 => 192.168.100.10:984 :: recv - len=6, ACK, seq=4d94bda4, ack=d89391ff
> Trace 192.168.100.30:1000 => 192.168.100.10:984 :: recv - len=6, ACK, seq=4d94bda4, ack=d89391ff
> Trace 192.168.100.30:1000 => 192.168.100.10:984 :: recv - len=6, ACK, seq=4d94bda4, ack=d89391ff
> Trace 192.168.100.30:1000 => 192.168.100.10:984 :: recv - len=6, ACK, seq=4d94bda4, ack=d89391ff
> Trace 192.168.100.30:1000 => 192.168.100.10:987 :: recv - len=6, RST,ACK, seq=3c1ad9f9, ack=72ac2609
>  Warn 192.168.100.30:1000 => 192.168.100.10:987 :: connection destroyed (received RST)
> Trace 192.168.100.30:1000 => 192.168.100.10:985 :: recv - len=6, ACK, seq=97c0fde0, ack=5b5c6053
> Trace 192.168.100.30:1000 => 192.168.100.10:984 :: recv - len=6, ACK, seq=4d94bda4, ack=d89391ff
> Trace 192.168.100.30:1000 => 192.168.100.10:986 :: recv - len=6, RST,ACK, seq=773fb2b5, ack=da1fc163
>  Warn 192.168.100.30:1000 => 192.168.100.10:986 :: connection destroyed (received RST)
> Trace 192.168.100.30:1000 => 192.168.100.10:984 :: recv - len=6, ACK, seq=4d94bda4, ack=d89391ff
> Trace 192.168.100.30:1000 => 192.168.100.10:985 :: recv - len=6, RST,ACK, seq=97c0fde1, ack=5b5c6053
>  Warn 192.168.100.30:1000 => 192.168.100.10:985 :: connection destroyed (received RST)
> Trace 192.168.100.30:1000 => 192.168.100.10:984 :: recv - len=6, RST,ACK, seq=4d94bda5, ack=d89391ff
>  Warn 192.168.100.30:1000 => 192.168.100.10:984 :: connection destroyed (received RST)
>

**Comment by hack3ric** [comment]
```
Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=6, RST, seq=40a55eeb, ack=00000000

Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=2, SYN,ACK, seq=059c614d, ack=062be55e
```

I'm *really* curious how RST and SYN packets can carry some data and have its length not 0. Mimic does that previously, but it is changed long ago. Also how does masquerade NAT allocate ports <1024? I could be wrong but this seems irrational. Maybe I should read Linux source code to find out.

With the above said, I still believe it is due to some sort of IP/port conflict, or mishandling of packets. I personally use Mimic along with masquerade NAT 24/7 even with firewall on, and I had no problems with it. Closing the issue for now since it shouldn't be Mimic's problem.

p.s. You could try Mimic v0.3.1, udp2raw or phantun to see if they work. Feel free to leave comments here if you have progress diagnosing the issue.

**Comment by Handsome1080P** [comment]
> ```
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=6, RST, seq=40a55eeb, ack=00000000
> 
> Trace 192.168.133.189:1000 => 192.168.100.30:1000 :: recv - len=2, SYN,ACK, seq=059c614d, ack=062be55e
> ```
> 
> I'm _really_ curious how RST and SYN packets can carry some data and have its length not 0. Mimic does that previously, but it is changed long ago. Also how does masquerade NAT allocate ports <1024? I could be wrong but this seems irrational. Maybe I should read Linux source code to find out.
> 
> With the above said, I still believe it is due to some sort of IP/port conflict, or mishandling of packets. I personally use Mimic along with masquerade NAT 24/7 even with firewall on, and I had no problems with it. Closing the issue for now since it shouldn't be Mimic's problem.
> 
> p.s. You could try Mimic v0.3.1, udp2raw or phantun to see if they work. Feel free to leave comments here if you have progress diagnosing the issue.
udp2raw and phantun all work,but not got the best performance.

**Comment by Handsome1080P** [comment]
Got how to use now.The example so simple.
