### ISSUE TITLE
How to use MIMIC forward traffic to another server?

### ISSUE THREAD

**Issue by Handsome1080P** [hack3ric/mimic#7]
The UDP Services not on local server.Like this:
192.168.100.254 Running MIMIC
192.168.100.253 Running UDP Services
how to use MIMIC,foward UDP traffic to another server?

**Comment by hack3ric** [comment]
You can't currently, ref: https://github.com/hack3ric/mimic/issues/5#issuecomment-2128503079

**Comment by hack3ric** [comment]
Thanks for the issue! I learnt `IP_FREEBIND` some time ago and now I'm adding it to Mimic. This scenario should be possible now.
